# Nams your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "astrafy_dbt_demo"
version: "1.1.1"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "astrafy"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.8.0", "<2.0.0"]

query-comment:
  comment: "{{ query_comment(node) }}"
  job-label: True

quoting:
  database: true
  schema: true
  identifier: true

vars:
  'dbt_date:time_zone': "Europe/Paris"

models:
  +tags: demo_dbt
  astrafy_dbt_demo:
    +tags:
      - jaffle_shop
    staging:
      +persist_docs:
        relation: true
        columns: true
      +materialized: table
    datamart:
      +materialized: table

  elementary:
    +enabled: true

  dbt_project_evaluator:
    +enabled: true

seeds:
  +tags: demo_dbt
  astrafy_dbt_demo:
    +persist_docs:
      relation: true
      columns: true

data_tests:
  +tags: demo_dbt
  +store_failures: true

flags:
  require_explicit_package_overrides_for_builtin_materializations: false